### ISSUE TITLE
Add explanation what slaac is and when to use

### ISSUE THREAD

**Issue by CodingSpiderFox** [proxmox/pve-docs#1]
When creating a container in the UI, the network section contains an option "slaac" for IPv6. The Help button page should explain a bit what this is and when it's usually used

**Comment by ThomasLamprecht** [comment]
Hi,

This is a sensible request, but GitHub is only used as mirror, please direct guture issues to one of the places linked in:
https://pve.proxmox.com/pve-docs/pve-admin-guide.html#getting_help

The Bug/Feature tracker would be probably best here:
https://bugzilla.proxmox.com/

thanks!
